<?php
/* @var $form \Base\Form\AbstractForm */
if ($form instanceof \Base\Form\AbstractForm) {
    if (!$form->getIsInitialized()) {
        $form->init();
    }
    
    $formId = $form->getAttribute('id');
    
    if (empty($formId)) {
        // domyślny id formularza - wygenerowany na podstawie nazwy klasy
        $formId = $form->getFormId();
        $form->setAttribute('id', $formId);
    }

    $elements = $form->getElements();
    $fieldsets = $form->getFieldsets();
    
    $buttons = [];

    $buttonTypes = [
        \Laminas\Form\Element\Submit::class,
        \Laminas\Form\Element\Button::class,
    ];
    
    $specialElements = [
        \Laminas\Form\Element\Csrf::class,
        \Laminas\Form\Element\Hidden::class,
    ];

    echo '<div class="form-container">';

    echo $this->form()->openTag($form);

    foreach ($elements as $element) {
        /* @var $element \Laminas\Form\Element */
        if (in_array(get_class($element), $buttonTypes)) {
            $buttons[] = $element;
            continue;
        }
        
        $elementId = $element->getAttribute('id');
        
        if (empty($elementId)) {
            // w przypadku gdy nie przypisano bezpośrednio id elementu z prefixem w postaci id formularza
            $elementId = $element->getName();
            $element->setAttribute('id', $formId . '_' . $elementId);
        }
        
        if (in_array(get_class($element), $specialElements)) {
            // elementy specjalne do wyrenderowania "od razu" jako ukryte
            echo $this->formElement($element);
            continue;
        }

        echo '<div class="mb-3 form-element-container ' . ($rowLabelClass ?? '') . '">';

        echo $this->formLabel($element);

        echo $this->formElement($element);
        echo $this->formElementErrors($element, ['id' => 'form-input-errors']);

        echo '</div>';
    }
    
    if (!empty($fieldsets)) {
        foreach ($fieldsets as $fieldset) {
            /* @var $fieldset \Base\Form\AbstractForm */
            echo $this->partial('base/form/fieldset', ['fieldset' => $fieldset]);
        }
    }

    if (!empty($buttons)) {
        echo '<div class="p-3 bg-body-tertiary">';

        foreach ($buttons as $button) {
            echo $this->formElement($button);
        }

        echo '</div>';
    }

    echo $this->form()->closeTag();

    echo '</div>';
}

