<?php
/* @var $form \Base\Form\AbstractForm */
if ($form instanceof \Base\Form\AbstractForm) {
    if (!$form->getIsInitialized()) {
        $form->init();
    }

    $elements = $form->getElements();
    $buttons = [];

    $buttonTypes = [
        \Laminas\Form\Element\Submit::class,
        \Laminas\Form\Element\Button::class,
    ];
    
    $specialElements = [
        \Laminas\Form\Element\Csrf::class,
        \Laminas\Form\Element\Hidden::class,
    ];

    echo '<div class="form-container">';

    echo $this->form()->openTag($form);

    echo '<table class="table">';

    foreach ($elements as $element) {
        if (in_array(get_class($element), $buttonTypes)) {
            $buttons[] = $element;
            continue;
        }
        
        if (in_array(get_class($element), $specialElements)) {
            // elementy specjalne do wyrenderowania "od razu" jako ukryte
            echo $this->formElement($element);
            continue;
        }

        echo '<tr>';

        echo '<td class="' . $rowLabelClass . '">';
        echo $this->formLabel($element);
        echo '</td>';

        echo '<td>';
        echo $this->formElement($element);
        echo $this->formElementErrors($element, ['id' => 'form-input-errors']);
        echo '</td>';

        echo '</tr>';
    }

    if (!empty($buttons)) {
        echo '<tr>';
        echo '<td colspan="2">';

        foreach ($buttons as $button) {
            echo $this->formElement($button);
            echo '&nbsp;';
        }

        echo '</td>';
        echo '</tr>';
    }

    echo '</table>';

    echo $this->form()->closeTag();

    echo '</div>';
}

