<?php
/* @var $navbar \Base\Navigation\Navigation */
$pages = $navbar->getPages();
$brandIcon = $navbar->getBrandIcon();
?>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <?php if (!empty($brandIcon)) : ?>
        <a class="navbar-brand" href="<?php echo $this->url($brandIcon->getRouteName(), array_merge($brandIcon->getParams(), ['action' => $brandIcon->getAction()])); ?>">
            <img src="<?php echo $brandIcon->getSrc(); ?>" alt="" width="<?php echo $brandIcon->getWidth(); ?>" height="<?php echo $brandIcon->getHeight(); ?>" class="d-inline-block align-text-top">
            <?php echo $brandIcon->getTitle(); ?>
        </a>
        <?php endif; ?>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <?php foreach ($pages as $page) : ?>
            <?php 
            /* @var $page \Base\Navigation\Page\Mvc */ 
            $hasChildrens = !empty($page->getPages());
            
            if (!$page->isAllowed()) {
                continue;
            }
            ?>
                <li class="nav-item <?php echo $hasChildrens ? 'dropdown' : ''; ?>">
                    <a 
                        class="nav-link <?php echo $hasChildrens ? 'dropdown-toggle' : ''; ?>" 
                        href="<?php echo $this->url($page->getRoute(), ['action' => $page->getAction()]); ?>"
                        <?php echo $hasChildrens ? 'data-bs-toggle="dropdown"' : ''; ?>
                    >
                        <?php echo $page->getLabel(); ?>
                        
                    </a>
                    <?php if ($hasChildrens) : ?>
                    <?php echo $this->partial('base/navbar_submenu', ['page' => $page, 'depth' => 1]); ?>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
</nav>
