<?php

foreach ($navigation as $page) {
    $page = new \Base\Navigation\Page\Mvc(array_merge($page, [
        'serviceManager' => $this->serviceManager(),
    ]));

    if ($page->isAllowed() && $page->isShowable()) {
        $class = $page->getClass();
        
        echo '<a href="' . $page->getHref() . '" class="btn btn-outline-primary ' . $class . '">';
        echo $page->getLabel();
        echo '</a>&nbsp;';
    }
}
