<?php
/* @var $paginator \Base\Paginator */
if ($paginator instanceof \Base\Paginator) {
    if (!$paginator->getIsInitialized()) {
        $paginator->init();
    }
    
    $form = $paginator->getFilterForm();
    
    if ($form instanceof \Base\Form\AbstractForm) {
        echo '<div class="mb-4">';
        echo $this->partial('base/paginator_filter', ['form' => $form]);
        echo '</div>';
    }

    $totalResults = $paginator->getTotalResults();

    if ($totalResults > 0) {
        $data = $paginator->getData();

        echo $this->partial('base/paginator_navigation', ['paginator' => $paginator]);

        echo $this->partial('base/table', [
            'data' => $data,
            'headers' => $paginator->getHeaders(),
            'index' => $paginator->getItemsPerPage() * ($paginator->getCurrentPage() - 1) + 1,
            'responsive' => $paginator->getIsResponsive(),
        ]);
    } else {

    }
}