<?php
/* @var $paginator \Base\Paginator */
$currentPage = $paginator->getCurrentPage();
$totalPages = $paginator->getTotalPages();
$firstPage = $paginator->getFirstPageInRange();
$lastPage = $paginator->getLastPageInRange();
$totalResults = $paginator->getTotalResults();
$loadTime = $paginator->getPageLoadTimeMs();
$perPageOptions = $paginator->getPerPageOptions();
$perPage = $paginator->getItemsPerPage();
?>
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item <?php echo $currentPage <= 1 ? 'disabled' : null; ?>">
            <a class="page-link" href="<?php echo $this->url(null, [], ['query' => ['page' => $currentPage - 1]], true); ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        
        <?php for ($i = $firstPage; $i <= $lastPage; $i++) : ?>
        <li class="page-item <?php echo ($currentPage == $i ? 'active' : null) ?>">
            <a class="page-link" href="<?php echo $this->url(null, [], ['query' => ['page' => $i]], true); ?>"><?php echo $i; ?></a>
        </li>
        <?php endfor; ?>
        
        <li class="page-item <?php echo $currentPage >= $totalPages ? 'disabled' : null; ?>">
            <a class="page-link" href="<?php echo $this->url(null, [], ['query' => ['page' => $currentPage + 1]], true); ?>" aria-label="Next">
                <span class="sr-only">Next</span>
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        
        <li class="page-item disabled">
            <span class="page-link">Strona <strong><?php echo $currentPage; ?></strong>  z <strong><?php echo $totalPages; ?></strong></span>
        </li>
        
        <li class="page-item disabled">
            <span class="page-link">Wyników na stronę </span>
        </li>
        
        <li class="page-item">
            <select name="items_per_page" class="form-control">
                <?php foreach ($perPageOptions as $option) : ?>
                    <option value="<?php echo $option; ?>" <?php echo ($perPage == $option ? 'selected' : null); ?>><?php echo $option; ?></option>
                <?php endforeach; ?>
            </select>
        </li>
        
        <li class="page-item disabled">
            <span class="page-link">Wyników <strong><i class="fas fa-hashtag"></i><?php echo $totalResults; ?></strong></span>
        </li>
        
        <li class="page-item disabled">
            <span class="page-link"><strong><i class="far fa-clock"></i></strong> <?php echo number_format($loadTime, 4); ?> s</span>
        </li>
        
        <li class="page-item disabled pl-2 hidden paginator-loader">
            <div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </li>
        
    </ul>
</nav>

