<?php
/* @var $paginator \Base\Paginator */
if ($paginator instanceof \Base\Paginator) {
    if (!$paginator->getIsInitialized()) {
        $paginator->init();
    }
    
    $ajaxUrl = $paginator->getAjaxUrl();
    $storageContainerName = $paginator->getStorageContainerName();
    $paginatorId = $paginator->getPaginatorId();
    $tableActionsPartial = $paginator->getTableActionsPartial();
    
    $form = $paginator->getFilterForm();
    
    if ($form instanceof \Base\Form\AbstractForm) {
        echo '<div class="mb-4">';
        echo $this->partial('base/paginator_filter', ['form' => $form, 'paginator' => $paginator]);
        echo '</div>';
    }

    $totalResults = $paginator->getTotalResults();

    if ($totalResults > 0) {
        $data = $paginator->getData();

        echo '<div id="' . $paginatorId . '">';
        
        echo $this->partial('base/paginator_navigation', ['paginator' => $paginator]);

        echo $this->partial('base/table', [
            'data' => $data,
            'headers' => $paginator->getHeaders(),
            'index' => $paginator->getItemsPerPage() * ($paginator->getCurrentPage() - 1) + 1,
            'responsive' => $paginator->getIsResponsive(),
            'table_actions_partial' => $tableActionsPartial,
            'ajax_url' => $ajaxUrl,
            'ajax_params' => json_encode(['paginatorId' => $paginatorId]),
            'sort' => $paginator->getSortingData(),
        ]);
        
        echo '</div>';
    } else {
        echo $paginator->getNoResultsText();
    }
    
    $this->inlineScript()->captureStart();
echo <<<"JS"
    $('#{$paginatorId}').find('select[name="items_per_page"]').on("change", function() {
        let itemsPerPage = $(this).val();
        $(this).prop('disabled', true);
        $(this).closest('nav').find('.paginator-loader').show();
    
        $.ajax({
            url: '{$ajaxUrl}',
            type: "POST",
            data: {paginatorId: '{$paginatorId}', itemsPerPage: itemsPerPage},
            success: function(response) {
                window.location.reload(true);
            }
        });
    });
JS;
    $this->inlineScript()->captureEnd();
}
