<?php
/* @var $paginator \Base\Paginator */
$currentPage = $paginator->getCurrentPage();
$totalPages = $paginator->getTotalPages();
$firstPage = $paginator->getFirstPageInRange();
$lastPage = $paginator->getLastPageInRange();
?>
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item <?php echo $currentPage <= 1 ? 'disabled' : null; ?>">
            <a class="page-link" href="<?php echo $this->url(null, [], ['query' => ['page' => $currentPage - 1]], true); ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        
        <?php for ($i = $firstPage; $i <= $lastPage; $i++) : ?>
        <li class="page-item <?php echo ($currentPage == $i ? 'active' : null) ?>">
            <a class="page-link" href="<?php echo $this->url(null, [], ['query' => ['page' => $i]], true); ?>"><?php echo $i; ?></a>
        </li>
        <?php endfor; ?>
        
        <li class="page-item <?php echo $currentPage >= $totalPages ? 'disabled' : null; ?>">
            <a class="page-link" href="<?php echo $this->url(null, [], ['query' => ['page' => $currentPage + 1]], true); ?>" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>

