<?php
/* @var $data \Laminas\Db\ResultSet\ResultSet */
$prototype = $data->getArrayObjectPrototype();
/* @var $prototype \Base\Db\Table\AbstractEntity */

$index = isset($index) ? $index : 1;
$headersMapping = $prototype->getHeadersMapping();
$rowActions = $prototype->getRowActions();
$rowDictionaries = $prototype->getDictionaries();

$dictionaries = [];

foreach ($rowDictionaries as $key => $rowDictionary) {
    $dictionary = $this->serviceManager()->get(\Base\Dictionary::class);
    /* @var $dictionary \Base\Dictionary */
    if (!empty($rowDictionary['name'])) {
        $dictionary->setDictionaryName($rowDictionary['name']);
    }
    
    if (!empty($rowDictionary['id'])) {
        $dictionary->setIdKey($rowDictionary['id']);
    }
    
    if (!empty($rowDictionary['modelName'])) {
        $dictionary->setModelName($rowDictionary['modelName']);
    }
    
    if (!empty($rowDictionary['nameFields'])) {
        $dictionary->setNameFields($rowDictionary['nameFields']);
    }
    
    if (!empty($rowDictionary['where'])) {
        $dictionary->setWhere($rowDictionary['where']);
    }
    
    if (!empty($rowDictionary['separator'])) {
        $dictionary->setSeparator($rowDictionary['separator']);
    }
    
    $dictionaries[$key] = $dictionary->getDictionary();
}

echo '<table class="table">';
echo '<thead>';
echo '<tr>';
echo '<th>#</th>';

foreach ($headers as $header) {
    echo '<th>';
    echo $headersMapping[$header]['title'];
    echo '</th>';
}

if (!empty($rowActions)) {
    echo '<th>Actions</th>';
}

echo '</tr>';
echo '</thead>';

echo '<tbody>';

foreach ($data as $row) {
    echo '<tr>';
    echo '<td>' . ($index++) . '</td>';
    
    foreach ($headers as $header) {
        $value = $row->{$header};
        
        if (!empty($dictionaries[$header][$row->{$header}])) {
            $value = $dictionaries[$header][$row->{$header}];
        }
        
        if (!empty($headersMapping[$header]['format'])) {
            $value = $this->format()->format($headersMapping[$header]['format'], $value);
        }
        
        echo '<td>';
        echo $value;
        echo '</td>';
    }
    
    if (!empty($rowActions)) {
        echo '<td class="text-nowrap">';
        echo $this->partial('base/table_actions', ['actions' => $rowActions, 'row' => $row]);
        echo '</td>';
    }
    
    echo '</tr>';
}

echo '</tbody>';

echo '</table>';
