<div class="dropdown">
    <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fas fa-cog"></i>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <?php
    $showedPages = [];

    foreach ($actions as $action) {
        $page = new \Base\Navigation\Page\Mvc(array_merge($action, [
            'row' => $row,
            'serviceManager' => $this->serviceManager(),
        ]));

        if ($page->isAllowed() && $page->isShowable() && !in_array($page->getHref(), $showedPages)) {
            $showedPages[] = $page->getHref();

            echo '<li>';
            echo '<a href="' . $page->getHref() . '" class="dropdown-item">';
            echo $page->getLabel();
            echo '</a>';
            echo '</li>';
        }
    }
    ?>
    </ul>
</div>
