<?php
/* @var $data \Laminas\Db\ResultSet\ResultSet */
$prototype = $data->getArrayObjectPrototype();
/* @var $prototype \Base\Db\Table\AbstractEntity */

$index = isset($index) ? $index : 1;
$headersMapping = $prototype->getHeadersMapping();
$rowActions = $prototype->getRowActions();
$rowDictionaries = $prototype->getDictionaries();
$sort = isset($sort) ? $sort : [];
$ajaxUrl = isset($ajax_url) ? $ajax_url : null;
$ajaxParams = isset($ajax_params) ? $ajax_params : json_encode([]);
$tableId = isset($table_id) ? $table_id : uniqid();

if (empty($table_actions_partial)) {
    $table_actions_partial = $prototype->getActionsPartial();
}

$dictionaries = [];

foreach ($rowDictionaries as $key => $rowDictionary) {
    $dictionary = $this->serviceManager()->get(\Base\Dictionary::class);
    $dictionary->init();
    
    /* @var $dictionary \Base\Dictionary */
    if (!empty($rowDictionary['name'])) {
        $dictionary->setDictionaryName($rowDictionary['name']);
    }
    
    if (!empty($rowDictionary['id'])) {
        $dictionary->setIdKey($rowDictionary['id']);
    }
    
    if (!empty($rowDictionary['modelName'])) {
        $dictionary->setModelName($rowDictionary['modelName']);
    }
    
    if (!empty($rowDictionary['nameFields'])) {
        $dictionary->setNameFields($rowDictionary['nameFields']);
    }
    
    if (!empty($rowDictionary['where'])) {
        $dictionary->setWhere($rowDictionary['where']);
    }
    
    if (!empty($rowDictionary['separator'])) {
        $dictionary->setSeparator($rowDictionary['separator']);
    }
    
    $dictionaries[$key] = $dictionary->getDictionary();
}

if ($responsive) {
    echo '<div class="table-responsive-xxl">';
}

echo '<table class="table" id="' . $tableId . '">';
echo '<thead class="table-light">';
echo '<tr>';
echo '<th class="fw-bold">#</th>';

foreach ($headers as $header) {
    echo '<th class="fw-bold ' . (!empty($headersMapping[$header]['sortable']) ? 'sortable' : null) . '" data-column_name="' . $header . '">';
    
    if (!empty($headersMapping[$header]['sortable'])) {
        echo '<a href="#"> '; 
        
        if (array_key_exists($header, $sort) && $sort[$header] === 'ASC') {
            echo '<i class="fa fa-sort-up"></i> ';
        } else if (array_key_exists($header, $sort) && $sort[$header] === 'DESC') {
            echo '<i class="fa fa-sort-down"></i> ';
        } else {
            echo '<i class="fa fa-sort"></i> ';
        }
        
        echo $headersMapping[$header]['title'] . ' ';
        
        echo '</a>';
    } else {
        echo $headersMapping[$header]['title'];
    }
    
    echo '</th>';
}

if (!empty($rowActions)) {
    echo '<th class="fw-bold">Actions</th>';
}

echo '</tr>';
echo '</thead>';

echo '<tbody>';

foreach ($data as $row) {
    echo '<tr>';
    echo '<td><strong>' . ($index++) . '</strong></td>';
    
    foreach ($headers as $header) {
        $value = $row->{$header};
        $class = null;
        
        if (!empty($dictionaries[$header][$row->{$header}])) {
            $value = $dictionaries[$header][$row->{$header}];
        }
        
        if (!empty($headersMapping[$header]['format'])) {
            $value = $this->format()->format($headersMapping[$header]['format'], $value);
        }
        
        if (!empty($headersMapping[$header]['class'])) {
            $class = $headersMapping[$header]['class'];
        }
        
        echo '<td class="' . $class . '">';
        echo $value;
        echo '</td>';
    }
    
    if (!empty($rowActions)) {
        echo '<td class="text-nowrap">';
        echo $this->partial($table_actions_partial, ['actions' => $rowActions, 'row' => $row]);
        echo '</td>';
    }
    
    echo '</tr>';
}

echo '</tbody>';

echo '</table>';

if ($responsive) {
    echo '</div>';
}

$this->inlineScript()->captureStart();
echo <<<"JS"
    let ajaxUrl = "{$ajaxUrl}";
    let ajaxParams = $.parseJSON('{$ajaxParams}');

    $('#{$tableId}').find('thead th.sortable a').each(function() {
        $(this).on("click", function() {
           let columnName = $(this).closest('th').attr('data-column_name');
           let data = ajaxParams;
    
           data['columnName'] = columnName;
    
           $.ajax({
               url: ajaxUrl,
               type: "POST",
               data: data,
               success: function(response) {
                   window.location.reload(true);
               }
           });
    
           return false;
        });
    });
JS;
    $this->inlineScript()->captureEnd();
